import React from 'react';
import { Box, Typography, Container } from '@mui/material';

const TermsOfServicePage = () => {
  return (
    <Container>
      <Box sx={{ py: 4 }}>
        <Typography variant="h4" gutterBottom>
          Terms of Service
        </Typography>

        <Typography variant="h6" gutterBottom>
          1. General Information About the Website and Its Purpose
        </Typography>
        <Typography paragraph>
          The purpose of the website is to provide AI tools that help users automate tasks.
        </Typography>
        <Typography paragraph>
          Users must be older than 13 years old to use this website.
        </Typography>

        <Typography variant="h6" gutterBottom>
          2. User Accounts and Registration
        </Typography>
        <Typography paragraph>
          Users need to create an account to access the website and its services.
        </Typography>
        <Typography paragraph>
          Users must login via a third-party authentication service, from which we are provided a name and an email address.
        </Typography>
        <Typography paragraph>
          Users are responsible for their login credentials and the use of their account to access our website.
        </Typography>

        <Typography variant="h6" gutterBottom>
          3. Content and User Behavior
        </Typography>
        <Typography paragraph>
          Users use the tools on the site for their own benefit, and content they produce does not directly affect content on the site.
        </Typography>
        <Typography paragraph>
          Users should not use the tools for illegal activities or harassment.
        </Typography>
        <Typography paragraph>
          Users should not interact with our site via bots or attempt to hack the site or otherwise misuse the AI tools. Violations may lead to account suspension or termination.
        </Typography>

        <Typography variant="h6" gutterBottom>
          4. Payment and Subscription Services
        </Typography>
        <Typography paragraph>
          Users prepay for credits which can be used to run AI tools on the website. If users encounter service issues, or are dissatisfied with the service, they can request a refund via our contact page. Refunds will be issued if it is determined that our site's operation caused a technical issue negatively affecting the user.
        </Typography>
        <Typography paragraph>
          No refunds will be made based on content produced by AI. The user understands that AI tools may occasionally produce random, unexpected, or poor results. This risk is assumed by the user when they use our site.
        </Typography>

        <Typography variant="h6" gutterBottom>
          5. Intellectual Property
        </Typography>
        <Typography paragraph>
          We own all rights to the content on our website, including images, logos, text, layouts of AI tools, and forms.
        </Typography>
        <Typography paragraph>
          User content is not shared with other users, and users hold no intellectual property rights in the usage of our site.
        </Typography>
        <Typography paragraph>
          When using AI tools, user text may be fed into an AI model served by a third party. These third parties have their own terms of service for data usage. Therefore, users should avoid inputting sensitive data into our website's AI tools.
        </Typography>
        <Typography paragraph>
          Our website has third-party integrations for user sign-up/authentication, payment services, and AI tools.
        </Typography>

        <Typography variant="h6" gutterBottom>
          6. Limitation of Liability
        </Typography>
        <Typography paragraph>
          The website may experience technical issues or downtime on occasion. The results produced by the website’s AI tools may be random, unexpected, or poor. We do not make guarantees regarding the quality of AI-generated results.
        </Typography>
        <Typography paragraph>
          We are not responsible for content input into our AI tools or content generated by our AI tools. We are also not responsible for issues with third-party integrations such as authentication and payments.
        </Typography>
        <Typography paragraph>
          We take steps to protect privacy and data, as detailed in our Privacy Policy.
        </Typography>
        <Typography paragraph>
          We reserve the right to modify or terminate user accounts at any time if users are found to be violating the terms of service.
        </Typography>
        <Typography paragraph>
          We reserve the right to change these terms of service at any time, and users will be notified via email if any changes occur.
        </Typography>

        <Typography variant="h6" gutterBottom>
          7. Disputes
        </Typography>
        <Typography paragraph>
          Disputes will be resolved through mediation in the state of Washington.
        </Typography>

        <Typography variant="h6" gutterBottom>
          8. Indemnity
        </Typography>
        <Typography paragraph>
          Users agree to indemnify and hold us harmless from any claims or damages resulting from their use of the site.
        </Typography>

        <Typography variant="h6" gutterBottom>
          9. Force Majeure
        </Typography>
        <Typography paragraph>
          We are not responsible for issues beyond our control, such as major system outages or interruptions to our AI backend integrations.
        </Typography>

        <Typography variant="h6" gutterBottom>
          10. Communication
        </Typography>
        <Typography paragraph>
          We will send users emails regarding important information related to these Terms of Service, including changes to the terms or other relevant notifications.
        </Typography>
      </Box>
    </Container>
  );
};

export default TermsOfServicePage;